version: '2'

services:
  spark:
    image: docker.io/bitnami/spark:3
    container_name: spark
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
      - '7077:7077'
      - '4040:4040' # Web UI
    volumes:
      - ../target:/queries

  spark-worker:
    image: docker.io/bitnami/spark:3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    depends_on:
      - spark

  hdfs-master:
    build:
      context: ./hdfs
    image: fmancini/hdfs
    container_name: hdfs-master
    environment:
      - HDFS_MODE=master
      - 'HDFS_WORKERS=hdfs-worker-1,hdfs-worker-2,hdfs-worker-3'
    depends_on:
      - hdfs-worker-1
      - hdfs-worker-2
      - hdfs-worker-3
    ports:
      - 9870:9870
      - 54310:54310

  hdfs-worker-1:
    build:
      context: ./hdfs
    image: fmancini/hdfs
    environment:
      - HDFS_MODE=worker

  hdfs-worker-2:
    build:
      context: ./hdfs
    image: fmancini/hdfs
    environment:
      - HDFS_MODE=worker

  hdfs-worker-3:
    build:
      context: ./hdfs
    image: fmancini/hdfs
    environment:
      - HDFS_MODE=worker
      
  nifi:
    image: docker.io/apache/nifi
    container_name: nifi
    ports: 
      - '8085:8080' # Web UI
    volumes:
      - ./hdfs/config:/hdfs/config/
      - ./nifi/conf:/opt/nifi/nifi-current/conf
      - nifi-archive:/opt/nifi/nifi-current/conf/archive
      - ./nifi/JDBCDriver:/JDBCDriver

  cockroach-1:
    image: cockroachdb/cockroach
    container_name: cockroach-1
    ports:
      - '8090:8080' # Web UI
    command: start --insecure --join=cockroach-1,cockroach-2
    volumes:
      - ./cockroach:/db

  cockroach-2:
    image: cockroachdb/cockroach
    container_name: cockroach-2
    ports:
      - '8091:8080' # Web UI
    command: start --insecure --join=cockroach-1,cockroach-2

  init-cockroach:
    image: cockroachdb/cockroach
    container_name: init-cockroach
    volumes:
      - ./cockroach:/cockroach-config
    entrypoint: "/bin/bash"
    command: /cockroach-config/init.sh
    depends_on:
      - cockroach-1
      - cockroach-2

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000

volumes:
  nifi-archive:
