version: '3'

services:
  hdfs-master:
    build:
      context: .
    image: fmancini/hdfs
    container_name: hdfs-master
    environment:
      - HDFS_MODE=master
      - 'HDFS_WORKERS=hdfs-worker1,hdfs-worker2,hdfs-worker3'
    depends_on:
      - 'hdfs-worker1'
      - 'hdfs-worker2'
      - 'hdfs-worker3'
    volumes:
      -  ./data:/data
    ports:
      - 54310:54310
    networks:
      - default
      - cluster

  hdfs-worker1:
    build:
      context: .
    image: fmancini/hdfs
    container_name: hdfs-worker1
    environment:
      - HDFS_MODE=worker

  hdfs-worker2:
    build:
      context: .
    image: fmancini/hdfs
    container_name: hdfs-worker2
    environment:
      - HDFS_MODE=worker
    networks:
      - cluster
  hdfs-worker3:
    build:
      context: .
    image: fmancini/hdfs
    container_name: hdfs-worker3
    environment:
      - HDFS_MODE=worker


networks:
  cluster:
      name: cluster-net
